### ISSUE TITLE
How to add event using event store?

### ISSUE THREAD

**Issue by atha-github** [adrai/node-eventstore#120]
Unable to add events into eventstore. I try with this:
es.getEventStream('streamId', function(err, stream) {
	  stream.addEvent({ my: 'event' });
	  stream.addEvents([{ my: 'event2' }]);
	  stream.commit(function(err, stream) {
		console.log(stream.eventsToDispatch); // this is an array containing all added events in this commit.
	  });
	});
But showing error..
TypeError: Cannot read property 'find' of undefined
    at Mongo.getEventsByRevision (D:\App\node\project\node_modules\eventstore\lib\databases\mongodb.js:351:16)
    at Eventstore.getEventsByRevision (D:\App\node\project\node_modules\eventstore\lib\eventstore.js:250:16)
    at Eventstore.getEventStream (D:\App\node\project\node_modules\eventstore\lib\eventstore.js:284:10)
    at D:\App\node\project\server\routes\master.js:45:5
    at Layer.handle [as handle_request] (D:\App\node\project\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\App\node\project\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (D:\App\node\project\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\App\node\project\node_modules\express\lib\router\layer.js:95:5)
    at D:\App\node\project\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (D:\App\node\project\node_modules\express\lib\router\index.js:330:12)

**Comment by adrai** [comment]
did you call es.init() ?

**Comment by atha-github** [comment]
Yes, I found the issue. You are right @adrai, I have not called es.init().
One more thing.. 
have you any demo/example project/Source code for eventsourcing with this eventstore? That will help me to integrate properly as the documentation is too short(Not clear everything).

**Comment by adrai** [comment]
https://github.com/adrai/cqrs-sample

**Comment by atha-github** [comment]
Thank You so much.
